'use client';

import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import Navigation from '@/components/Navigation';
import { useAuthStore } from '@/lib/store';
import { ArrowLeft, Download, Calendar, DollarSign } from 'lucide-react';

interface Escrow {
  id: string;
  applicationId: string;
  companyId: string;
  candidateId: string;
  jobTitle: string;
  startDate: string;
  endDate: string;
  amount: string;
  currency: string;
  description: string;
  terms: string;
  status: string;
  confirmationStatus: 'pending' | 'confirmed';
  createdAt: string;
  updatedAt: string;
}

export default function EscrowViewPage() {
  const router = useRouter();
  const params = useParams();
  const escrowId = params.escrowId as string;
  const { user, isAuthenticated } = useAuthStore();

  const [escrow, setEscrow] = useState<Escrow | null>(null);
  const [loading, setLoading] = useState(true);
  const [daysRemaining, setDaysRemaining] = useState(0);
  const [confirming, setConfirming] = useState(false);

  useEffect(() => {
    fetchEscrow();
  }, [escrowId]);

  useEffect(() => {
    if (escrow) {
      const endDate = new Date(escrow.endDate);
      const today = new Date();
      const days = Math.ceil((endDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
      setDaysRemaining(Math.max(0, days));
    }
  }, [escrow]);

  const fetchEscrow = async () => {
    try {
      const response = await fetch('/api/escrow');
      if (response.ok) {
        const escrows = await response.json();
        console.log('All escrows:', escrows);
        console.log('Looking for escrowId:', escrowId);
        const found = escrows.find((e: Escrow) => e.id === escrowId);
        console.log('Found escrow:', found);
        setEscrow(found || null);
      } else {
        console.error('Failed to fetch escrows:', response.status);
      }
    } catch (error) {
      console.error('Error fetching escrow:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!escrow) return;

    const contractText = `
ESCROW CONTRACT

Contract ID: ${escrow.id}
Created: ${new Date(escrow.createdAt).toLocaleDateString()}

POSITION: ${escrow.jobTitle}

CONTRACT PERIOD:
Start Date: ${new Date(escrow.startDate).toLocaleDateString()}
End Date: ${new Date(escrow.endDate).toLocaleDateString()}
Duration: ${daysRemaining} days remaining

COMPENSATION:
Amount: ${escrow.amount} ${escrow.currency}
Currency: ${escrow.currency}

JOB DESCRIPTION:
${escrow.description}

TERMS & CONDITIONS:
${escrow.terms}

STATUS: ${escrow.status.toUpperCase()}

---
This is an automated escrow contract generated by JOBEZZY.
Both parties agree to the terms and conditions mentioned above.
    `;

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(contractText));
    element.setAttribute('download', `escrow_${escrow.id}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleConfirmContract = async () => {
    if (!escrow) return;

    setConfirming(true);
    try {
      const response = await fetch('/api/escrow', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: escrow.id,
          confirmationStatus: 'confirmed',
        }),
      });

      if (response.ok) {
        const updated = await response.json();
        setEscrow(updated);
        
        // Update application to mark contract as accepted
        await fetch('/api/applications', {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            id: escrow.applicationId,
            contractAccepted: true,
            contractAcceptedAt: new Date().toISOString(),
          }),
        });

        alert('Contract accepted! You are now hired.');
      } else {
        alert('Failed to confirm contract');
      }
    } catch (error) {
      console.error('Error confirming contract:', error);
      alert('Error confirming contract');
    } finally {
      setConfirming(false);
    }
  };

  const handleRejectContract = async (escrowId: string) => {
    if (!confirm('Are you sure you want to reject this contract?')) return;

    try {
      const response = await fetch('/api/escrow', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: escrowId,
          confirmationStatus: 'rejected',
        }),
      });

      if (response.ok) {
        alert('Contract rejected.');
        router.back();
      } else {
        alert('Failed to reject contract');
      }
    } catch (error) {
      console.error('Error rejecting contract:', error);
      alert('Error rejecting contract');
    }
  };

  if (!isAuthenticated || !user) return null;

  if (loading) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-dark-950 via-dark-900 to-dark-950">
        <Navigation />
        <div className="max-w-4xl mx-auto px-4 py-8 pb-32">
          <p className="text-dark-300">Loading contract...</p>
        </div>
      </main>
    );
  }

  if (!escrow) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-dark-950 via-dark-900 to-dark-950">
        <Navigation />
        <div className="max-w-4xl mx-auto px-4 py-8 pb-32">
          <p className="text-dark-300">Contract not found</p>
        </div>
      </main>
    );
  }

  const isExpired = daysRemaining === 0;

  // Debug logging
  console.log('Escrow:', escrow);
  console.log('User:', user);
  console.log('Confirmation Status:', escrow?.confirmationStatus);
  console.log('Candidate ID:', escrow?.candidateId);
  console.log('User ID:', user?.id);
  console.log('Should show buttons:', escrow?.confirmationStatus === 'pending' && escrow?.candidateId === user?.id);

  return (
    <main className="min-h-screen bg-gradient-to-br from-dark-950 via-dark-900 to-dark-950">
      <Navigation />

      <div className="max-w-4xl mx-auto px-4 py-8 pb-32">
        {/* Back Button */}
        <button
          onClick={() => router.back()}
          className="mb-8 p-2 rounded-lg hover:bg-white/10 transition-all inline-block"
        >
          <ArrowLeft size={24} className="text-primary-400" />
        </button>

        {/* Header */}
        <div className="mb-8 animate-fadeInUp">
          <div className="flex items-center justify-between mb-4">
            <h1 className="text-4xl font-bold gradient-text">Escrow Contract</h1>
            <div className="flex gap-2">
              <span className={`px-4 py-2 rounded-full font-bold ${
                isExpired
                  ? 'bg-red-500/20 text-red-300'
                  : 'bg-green-500/20 text-green-300'
              }`}>
                {isExpired ? 'Expired' : 'Active'}
              </span>
              <span className={`px-4 py-2 rounded-full font-bold ${
                escrow.confirmationStatus === 'confirmed'
                  ? 'bg-green-500/20 text-green-300'
                  : 'bg-yellow-500/20 text-yellow-300'
              }`}>
                {escrow.confirmationStatus === 'confirmed' ? '✓ Confirmed' : 'Pending Approval'}
              </span>
            </div>
          </div>
          <p className="text-dark-300">Contract ID: {escrow.id}</p>
        </div>

        {/* Contract Document */}
        <div className="glass-dark rounded-xl p-8 mb-8 animate-fadeInUp" style={{ animationDelay: '0.1s' }}>
          {/* Title */}
          <div className="border-b border-dark-700 pb-6 mb-6">
            <h2 className="text-3xl font-bold text-white mb-2">{escrow.jobTitle}</h2>
            <p className="text-dark-300">Escrow Contract Agreement</p>
          </div>

          {/* Contract Details */}
          <div className="space-y-6">
            {/* Timeline */}
            <div className="grid grid-cols-3 gap-4">
              <div className="bg-dark-800/50 rounded-lg p-4">
                <div className="flex items-center gap-2 mb-2">
                  <Calendar size={18} className="text-primary-400" />
                  <p className="text-dark-400 text-sm">Start Date</p>
                </div>
                <p className="text-white font-bold">{new Date(escrow.startDate).toLocaleDateString()}</p>
              </div>
              <div className="bg-dark-800/50 rounded-lg p-4">
                <div className="flex items-center gap-2 mb-2">
                  <Calendar size={18} className="text-accent-400" />
                  <p className="text-dark-400 text-sm">End Date</p>
                </div>
                <p className="text-white font-bold">{new Date(escrow.endDate).toLocaleDateString()}</p>
              </div>
              <div className="bg-dark-800/50 rounded-lg p-4">
                <p className="text-dark-400 text-sm mb-2">Days Remaining</p>
                <p className={`text-2xl font-bold ${isExpired ? 'text-red-400' : 'text-green-400'}`}>
                  {daysRemaining}
                </p>
              </div>
            </div>

            {/* Compensation */}
            <div className="bg-dark-800/50 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-4">
                <DollarSign size={20} className="text-primary-400" />
                <h3 className="text-xl font-bold text-white">Compensation</h3>
              </div>
              <div className="text-4xl font-bold gradient-text mb-2">
                {escrow.amount} {escrow.currency}
              </div>
              <p className="text-dark-300">Total contract value</p>
            </div>

            {/* Description */}
            {escrow.description && (
              <div>
                <h3 className="text-lg font-bold text-white mb-3">Job Description</h3>
                <div className="bg-dark-800/50 rounded-lg p-4">
                  <p className="text-dark-300 whitespace-pre-wrap">{escrow.description}</p>
                </div>
              </div>
            )}

            {/* Terms & Conditions */}
            {escrow.terms && (
              <div>
                <h3 className="text-lg font-bold text-white mb-3">Terms & Conditions</h3>
                <div className="bg-dark-800/50 rounded-lg p-4">
                  <p className="text-dark-300 whitespace-pre-wrap">{escrow.terms}</p>
                </div>
              </div>
            )}

            {/* Contract Info */}
            <div className="border-t border-dark-700 pt-6">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <p className="text-dark-400">Created</p>
                  <p className="text-white font-bold">{new Date(escrow.createdAt).toLocaleString()}</p>
                </div>
                <div>
                  <p className="text-dark-400">Last Updated</p>
                  <p className="text-white font-bold">{new Date(escrow.updatedAt).toLocaleString()}</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Buttons */}
        <div className="flex gap-4 animate-fadeInUp" style={{ animationDelay: '0.2s' }}>
          <button
            onClick={handleDownload}
            className="flex-1 py-3 px-6 bg-gradient-to-r from-primary-500 to-accent-500 hover:from-primary-600 hover:to-accent-600 text-white font-bold rounded-lg transition-all flex items-center justify-center gap-2"
          >
            <Download size={20} />
            Download Contract
          </button>

          {escrow.confirmationStatus === 'pending' && escrow.candidateId === user?.id && (
            <>
              <button
                onClick={handleConfirmContract}
                disabled={confirming}
                className="flex-1 py-3 px-6 bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 disabled:opacity-50 text-white font-bold rounded-lg transition-all flex items-center justify-center gap-2"
              >
                ✓ {confirming ? 'Confirming...' : 'Accept Contract'}
              </button>
              <button
                onClick={() => handleRejectContract(escrow.id)}
                className="flex-1 py-3 px-6 bg-gradient-to-r from-red-500 to-rose-500 hover:from-red-600 hover:to-rose-600 text-white font-bold rounded-lg transition-all flex items-center justify-center gap-2"
              >
                ✗ Reject Contract
              </button>
            </>
          )}

          {escrow.confirmationStatus === 'confirmed' && (
            <div className="flex-1 py-3 px-6 bg-green-500/20 text-green-300 font-bold rounded-lg flex items-center justify-center gap-2">
              ✓ Contract Confirmed
            </div>
          )}
        </div>
      </div>
    </main>
  );
}
